name: pubspec_lock
description: Dart library to access content of pubpec.lock files
version: 0.0.1
author: Alexei Sintotski
homepage:

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  dependency_validator: ^1.0.0
